// src/routes/(app)/todo/+page.svelte
<script lang="ts">
	import {
		ListTodo,
		Plus,
		Trash2,
		Pencil,
		Search,
		X,
		Check,
		Filter,
		FileText
	} from '@lucide/svelte';
	import * as InputGroup from '$lib/components/ui/input-group/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Separator } from '$lib/components/ui/separator/index.js';
	import { Checkbox } from '$lib/components/ui/checkbox/index.js';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { api } from '$lib/api.js';
	import { superForm } from 'sveltekit-superforms';

	let { data } = $props();

	type Todo = {
		_id: string;
		title: string;
		description?: string;
		isComplete: boolean;
		updatedAt: string;
	};

	const { form, errors, enhance, submitting, message, constraints } = superForm(data.form, {
		resetForm: true,
		invalidateAll: false
	});

	// ── State ─────────────────────────────────────────────
	let todos = $state<Todo[]>(data.todos);
	let loading = $state(false);
	let error = $state('');

	// filters
	let searchQuery = $state($page.url.searchParams.get('query') ?? '');
	let filterComplete = $state($page.url.searchParams.get('complete') ?? 'all');

	// edit state
	let editingId = $state<string | null>(null);
	let editTitle = $state('');
	let editDescription = $state('');

	// ── Sync todos when load() returns new data ───────────
	$effect(() => {
		todos = data.todos;
	});

	// ── Search/filter → update URL → re-runs load() ───────
	$effect(() => {
		const params = new URLSearchParams();
		if (searchQuery.trim()) params.set('query', searchQuery.trim());
		if (filterComplete !== 'all')
			params.set('complete', filterComplete === 'done' ? 'true' : 'false');

		goto(`?${params}`, { keepFocus: true, noScroll: true });
	});

	// ── Derived counts ────────────────────────────────────
	const doneCount = $derived(todos.filter((t) => t.isComplete).length);
	const pendingCount = $derived(todos.filter((t) => !t.isComplete).length);

	// Toggle complete status
	async function toggleTodo(id: string) {
		try {
			const res = await api.patch(`todos/toggle/status/${id}`, {});
			const json = await res.json();
			todos = todos.map((t) => (t._id === id ? json.data : t));
		} catch {
			error = 'failed to toggle todo.';
		}
	}

	// Delete a todo
	async function deleteTodo(id: string) {
		try {
			await api.del(`todos/${id}`);
			todos = todos.filter((t) => t._id !== id);
		} catch {
			error = 'failed to delete todo.';
		}
	}

	function startEdit(todo: Todo) {
		editingId = todo._id;
		editTitle = todo.title;
		editDescription = todo.description ?? '';
	}

	async function saveEdit(id: string) {
		try {
			const res = await api.patch(`todos/${id}`, {
				title: editTitle,
				description: editDescription
			});
			const json = await res.json();
			todos = todos.map((t) => (t._id === id ? json.data : t));
			editingId = null;
		} catch {
			error = 'failed to update todo.';
		}
	}

	function cancelEdit() {
		editingId = null;
	}
</script>

<div class="flex min-h-screen flex-col items-center px-4 py-12">
	<div class="flex w-full max-w-xl flex-col gap-6">
		<!-- Header -->
		<div class="flex items-center gap-2">
			<ListTodo class="h-5 w-5 text-sidebar-primary" />
			<h1 class="font-mono text-sm tracking-widest uppercase">todos</h1>
			<span class="ml-auto font-mono text-xs text-muted-foreground">
				{doneCount}/{todos.length} done
			</span>
		</div>

		<Separator class="opacity-20" />

		<!-- Create -->
		<form method="POST" use:enhance class="flex flex-col gap-2">
			<p class="font-mono text-xs tracking-widest text-muted-foreground uppercase">new</p>

			<div class="flex flex-col gap-1">
				<InputGroup.Root class={$errors.title ? 'border-destructive' : ''}>
					<InputGroup.Input
						type="text"
						name="title"
						placeholder="todo title"
						bind:value={$form.title}
					/>
					<InputGroup.Addon><FileText class="h-4 w-4" /></InputGroup.Addon>
				</InputGroup.Root>
				{#if $errors.title}
					<p class="font-mono text-xs text-destructive">{$errors.title}</p>
					<!-- ← here -->
				{/if}
			</div>

			<div class="flex flex-col gap-1">
				<InputGroup.Root>
					<InputGroup.Textarea
						name="description"
						placeholder="description (optional)"
						bind:value={$form.description}
					/>
				</InputGroup.Root>
				{#if $errors.description}
					<p class="font-mono text-xs text-destructive">{$errors.description}</p>
					<!-- ← here -->
				{/if}
			</div>

			{#if $message}
				<p
					class="font-mono text-xs"
					class:text-sidebar-primary={$message.type === 'success'}
					class:text-destructive={$message.type === 'error'}
				>
					{$message.text}
				</p>
			{/if}

			<Button
				variant="outline"
				disabled={$submitting}
				class="w-full gap-2 font-mono text-xs tracking-widest uppercase"
			>
				<Plus class="h-4 w-4" />
				{$submitting ? 'adding...' : 'add todo'}
			</Button>
		</form>

		<Separator class="opacity-20" />

		<!-- Search + Filter -->
		<div class="flex flex-col gap-2">
			<InputGroup.Root>
				<InputGroup.Input type="text" placeholder="search todos..." bind:value={searchQuery} />
				<InputGroup.Addon>
					{#if searchQuery}
						<button onclick={() => (searchQuery = '')}><X class="h-4 w-4" /></button>
					{:else}
						<Search class="h-4 w-4" />
					{/if}
				</InputGroup.Addon>
			</InputGroup.Root>

			<div class="flex gap-2">
				{#each ['all', 'pending', 'done'] as f}
					<Button
						variant={filterComplete === f ? 'default' : 'outline'}
						onclick={() => (filterComplete = f as typeof filterComplete)}
						class="flex-1 gap-1 font-mono text-xs tracking-widest uppercase"
					>
						<Filter class="h-3 w-3" />
						{f}
					</Button>
				{/each}
			</div>
		</div>

		<Separator class="opacity-20" />

		<!-- List -->
		<div class="flex flex-col gap-2">
			<div class="flex items-center gap-2">
				<p class="font-mono text-xs tracking-widest text-muted-foreground uppercase">
					{filterComplete === 'all' ? 'all' : filterComplete} · {todos.length} items
				</p>
				{#if loading}
					<span class="animate-pulse font-mono text-xs text-muted-foreground">loading...</span>
				{/if}
			</div>

			{#if error}
				<p class="font-mono text-xs text-destructive">{error}</p>
			{/if}

			{#if todos.length === 0 && !loading}
				<p class="py-4 text-center font-mono text-xs text-muted-foreground opacity-50">
					no todos found.
				</p>
			{/if}

			{#each todos as todo (todo._id)}
				<div
					class="flex flex-col gap-2 rounded-lg border border-border bg-card p-3 transition-opacity"
					class:opacity-50={todo.isComplete}
				>
					{#if editingId === todo._id}
						<!-- Edit mode -->
						<div class="flex flex-col gap-2">
							<InputGroup.Root>
								<InputGroup.Input type="text" bind:value={editTitle} placeholder="title" />
								<InputGroup.Addon><FileText class="h-4 w-4" /></InputGroup.Addon>
							</InputGroup.Root>
							<InputGroup.Root>
								<InputGroup.Input
									type="text"
									bind:value={editDescription}
									placeholder="description"
								/>
								<InputGroup.Addon><FileText class="h-4 w-4" /></InputGroup.Addon>
							</InputGroup.Root>
							<div class="flex gap-2">
								<Button
									variant="outline"
									onclick={() => saveEdit(todo._id)}
									class="flex-1 gap-1 font-mono text-xs tracking-widest uppercase"
								>
									<Check class="h-3 w-3" /> save
								</Button>
								<Button
									variant="outline"
									onclick={cancelEdit}
									class="flex-1 gap-1 font-mono text-xs tracking-widest uppercase"
								>
									<X class="h-3 w-3" /> cancel
								</Button>
							</div>
						</div>
					{:else}
						<!-- View mode -->
						<div class="flex items-start gap-3">
							<Checkbox
								checked={todo.isComplete}
								onCheckedChange={() => toggleTodo(todo._id)}
								class="mt-0.5"
							/>
							<div class="flex min-w-0 flex-1 flex-col gap-0.5">
								<p
									class="font-mono text-xs leading-relaxed"
									class:line-through={todo.isComplete}
									class:text-muted-foreground={todo.isComplete}
								>
									{todo.title}
								</p>
								{#if todo.description}
									<p class="truncate font-mono text-xs text-muted-foreground opacity-60">
										{todo.description}
									</p>
								{/if}
							</div>
							<div class="flex shrink-0 items-center gap-1">
								<Button variant="ghost" size="icon" onclick={() => startEdit(todo)} class="h-6 w-6">
									<Pencil class="h-3 w-3" />
								</Button>
								<Button
									variant="ghost"
									size="icon"
									onclick={() => deleteTodo(todo._id)}
									class="h-6 w-6 text-destructive hover:text-destructive"
								>
									<Trash2 class="h-3 w-3" />
								</Button>
							</div>
						</div>
					{/if}
				</div>
			{/each}
		</div>

		<!-- Footer stats -->
		{#if todos.length > 0}
			<Separator class="opacity-20" />
			<div class="flex justify-between font-mono text-xs text-muted-foreground">
				<span>{pendingCount} pending</span>
				<span>{doneCount} completed</span>
			</div>
		{/if}
	</div>
</div>

// mobile/app/(tabs)/todo.tsx
import {
	Text,
	TextInput,
	View,
	FlatList,
	TouchableOpacity,
	Alert,
	RefreshControl,
	Pressable,
	ActivityIndicator
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import React from 'react';
import { api } from '@/api';
import { useAuth } from '@/context/auth';

type Todo = {
	_id: string;
	title: string;
	description?: string;
	isComplete: boolean;
	updatedAt: string;
};

export default function TodoScreen() {
	const { token } = useAuth();

	const [todos, setTodos] = React.useState<Todo[]>([]);
	const [loading, setLoading] = React.useState(true);
	const [refreshing, setRefreshing] = React.useState(false);

	// Create form
	const [title, setTitle] = React.useState('');
	const [description, setDescription] = React.useState('');
	const [creating, setCreating] = React.useState(false);

	// Search & filter
	const [search, setSearch] = React.useState('');
	const [filter, setFilter] = React.useState<'all' | 'pending' | 'done'>('all');

	// Edit state
	const [editingId, setEditingId] = React.useState<string | null>(null);
	const [editTitle, setEditTitle] = React.useState('');
	const [editDesc, setEditDesc] = React.useState('');

	const debounceRef = React.useRef<NodeJS.Timeout | null>(null);

	React.useEffect(() => {
		fetchTodos();
	}, [filter]);

	React.useEffect(() => {
		if (debounceRef.current) clearTimeout(debounceRef.current);
		debounceRef.current = setTimeout(() => {
			fetchTodos();
		}, 400);
		return () => {
			if (debounceRef.current) clearTimeout(debounceRef.current);
		};
	}, [search]);

	async function fetchTodos() {
		try {
			const params = new URLSearchParams();
			if (search.trim()) params.set('query', search.trim());
			if (filter === 'done') params.set('complete', 'true');
			if (filter === 'pending') params.set('complete', 'false');

			const res = await api.get(`todos?${params}`, token);
			const json = await res.json();
			if (res.ok) {
				setTodos(json.data ?? []);
			}
		} catch {
			Alert.alert('Error', 'Failed to load todos');
		} finally {
			setLoading(false);
			setRefreshing(false);
		}
	}

	async function createTodo() {
		if (!title.trim()) {
			Alert.alert('Error', 'Title is required');
			return;
		}
		setCreating(true);
		try {
			const res = await api.post(
				'todos',
				{ title: title.trim(), description: description.trim() || undefined },
				token
			);
			if (res.ok) {
				const json = await res.json();
				setTodos((prev) => [json.data, ...prev]);
				setTitle('');
				setDescription('');
			} else {
				const json = await res.json();
				Alert.alert('Error', json.message || 'Failed to create todo');
			}
		} catch {
			Alert.alert('Error', 'Failed to create todo');
		} finally {
			setCreating(false);
		}
	}

	async function toggleTodo(id: string) {
		try {
			const res = await api.patch(`todos/toggle/status/${id}`, {}, token);
			const json = await res.json();
			if (res.ok) {
				setTodos((prev) => prev.map((t) => (t._id === id ? json.data : t)));
			}
		} catch {
			Alert.alert('Error', 'Failed to toggle todo');
		}
	}

	async function deleteTodo(id: string) {
		Alert.alert('Delete Todo', 'Are you sure?', [
			{ text: 'Cancel', style: 'cancel' },
			{
				text: 'Delete',
				style: 'destructive',
				onPress: async () => {
					try {
						await api.del(`todos/${id}`, token);
						setTodos((prev) => prev.filter((t) => t._id !== id));
					} catch {
						Alert.alert('Error', 'Failed to delete todo');
					}
				}
			}
		]);
	}

	function startEdit(todo: Todo) {
		setEditingId(todo._id);
		setEditTitle(todo.title);
		setEditDesc(todo.description ?? '');
	}

	async function saveEdit(id: string) {
		try {
			const res = await api.patch(
				`todos/${id}`,
				{ title: editTitle, description: editDesc || undefined },
				token
			);
			const json = await res.json();
			if (res.ok) {
				setTodos((prev) => prev.map((t) => (t._id === id ? json.data : t)));
				setEditingId(null);
			}
		} catch {
			Alert.alert('Error', 'Failed to update todo');
		}
	}

	const doneCount = todos.filter((t) => t.isComplete).length;
	const pendingCount = todos.filter((t) => !t.isComplete).length;

	function renderTodo({ item: todo }: { item: Todo }) {
		if (editingId === todo._id) {
			return (
				<View className="mb-2 rounded-2xl border border-gray-100 bg-white p-4">
					<TextInput
						className="mb-2 rounded-xl border border-gray-100 bg-gray-50 px-3 py-2 text-sm"
						value={editTitle}
						onChangeText={setEditTitle}
						placeholder="Title"
						placeholderTextColor="#9ca3af"
					/>
					<TextInput
						className="mb-2 rounded-xl border border-gray-100 bg-gray-50 px-3 py-2 text-sm"
						value={editDesc}
						onChangeText={setEditDesc}
						placeholder="Description"
						placeholderTextColor="#9ca3af"
					/>
					<View className="flex-row gap-2">
						<TouchableOpacity
							onPress={() => saveEdit(todo._id)}
							className="flex-1 items-center rounded-xl bg-blue-500 py-2"
						>
							<Text className="text-sm font-semibold text-white">Save</Text>
						</TouchableOpacity>
						<TouchableOpacity
							onPress={() => setEditingId(null)}
							className="flex-1 items-center rounded-xl bg-gray-200 py-2"
						>
							<Text className="text-sm font-semibold text-gray-700">Cancel</Text>
						</TouchableOpacity>
					</View>
				</View>
			);
		}

		return (
			<View
				className={`mb-2 rounded-2xl border border-gray-100 bg-white p-4 ${
					todo.isComplete ? 'opacity-50' : ''
				}`}
			>
				<View className="flex-row items-start">
					{/* Checkbox */}
					<Pressable onPress={() => toggleTodo(todo._id)} className="mt-0.5 mr-3">
						<View
							className={`h-5 w-5 items-center justify-center rounded-md border-2 ${
								todo.isComplete ? 'border-blue-500 bg-blue-500' : 'border-gray-300'
							}`}
						>
							{todo.isComplete && <Text className="text-xs text-white">✓</Text>}
						</View>
					</Pressable>

					{/* Content */}
					<View className="flex-1">
						<Text
							className={`text-sm font-medium ${
								todo.isComplete ? 'text-gray-400 line-through' : 'text-gray-900'
							}`}
						>
							{todo.title}
						</Text>
						{todo.description ? (
							<Text className="mt-0.5 text-xs text-gray-400" numberOfLines={1}>
								{todo.description}
							</Text>
						) : null}
					</View>

					{/* Actions */}
					<View className="ml-2 flex-row gap-3">
						<Pressable onPress={() => startEdit(todo)} hitSlop={8}>
							<Text className="text-xs text-gray-400">Edit</Text>
						</Pressable>
						<Pressable onPress={() => deleteTodo(todo._id)} hitSlop={8}>
							<Text className="text-xs text-red-400">Delete</Text>
						</Pressable>
					</View>
				</View>
			</View>
		);
	}

	return (
		<SafeAreaView className="flex-1 bg-gray-50">
			{/* Header */}
			<View className="border-b border-gray-100 bg-white px-4 pt-4 pb-3">
				<View className="mb-3 flex-row items-center justify-between">
					<Text className="text-lg font-bold text-gray-900">Todos</Text>
					<Text className="text-xs text-gray-400">
						{doneCount}/{todos.length} done
					</Text>
				</View>

				{/* Create */}
				<TextInput
					className="mb-2 rounded-xl border border-gray-100 bg-gray-50 px-4 py-2.5 text-sm"
					placeholder="Todo title"
					placeholderTextColor="#9ca3af"
					value={title}
					onChangeText={setTitle}
				/>
				<TextInput
					className="mb-2 rounded-xl border border-gray-100 bg-gray-50 px-4 py-2.5 text-sm"
					placeholder="Description (optional)"
					placeholderTextColor="#9ca3af"
					value={description}
					onChangeText={setDescription}
				/>
				<TouchableOpacity
					onPress={createTodo}
					disabled={creating || !title.trim()}
					className={`mb-3 items-center rounded-xl py-2.5 ${
						creating || !title.trim() ? 'bg-blue-200' : 'bg-blue-500'
					}`}
				>
					<Text className="text-sm font-semibold text-white">
						{creating ? 'Adding...' : 'Add Todo'}
					</Text>
				</TouchableOpacity>

				{/* Search */}
				<TextInput
					className="mb-2 rounded-xl border border-gray-100 bg-gray-50 px-4 py-2.5 text-sm"
					placeholder="Search todos..."
					placeholderTextColor="#9ca3af"
					value={search}
					onChangeText={setSearch}
				/>

				{/* Filter */}
				<View className="flex-row gap-2">
					{(['all', 'pending', 'done'] as const).map((f) => (
						<TouchableOpacity
							key={f}
							onPress={() => setFilter(f)}
							className={`flex-1 items-center rounded-xl py-2 ${
								filter === f ? 'bg-blue-500' : 'bg-gray-100'
							}`}
						>
							<Text
								className={`text-xs font-semibold capitalize ${
									filter === f ? 'text-white' : 'text-gray-600'
								}`}
							>
								{f}
							</Text>
						</TouchableOpacity>
					))}
				</View>
			</View>

			{/* Todo list */}
			<FlatList
				data={todos}
				keyExtractor={(item) => item._id}
				renderItem={renderTodo}
				contentContainerClassName="px-4 pt-3 pb-4"
				refreshControl={
					<RefreshControl
						refreshing={refreshing}
						onRefresh={() => {
							setRefreshing(true);
							fetchTodos();
						}}
					/>
				}
				ListEmptyComponent={
					loading ? (
						<Text className="py-8 text-center text-gray-400">Loading...</Text>
					) : (
						<Text className="py-8 text-center text-gray-400">No todos found.</Text>
					)
				}
				ListFooterComponent={
					todos.length > 0 ? (
						<View className="flex-row justify-between px-1 py-2">
							<Text className="text-xs text-gray-400">{pendingCount} pending</Text>
							<Text className="text-xs text-gray-400">{doneCount} completed</Text>
						</View>
					) : null
				}
			/>
		</SafeAreaView>
	);
}
